### PR TITLE
Repository ID handling improvement

### LINKED ISSUE #1564: RepositoryID with slash in it
### Affected version

All

### Bug description

I just found a POM that defines a repository with slash (`/`) in repository ID, that is invalid character for Maven ID fields. 

This breaks:
* split repository
* RRF prefix caching

### PR DESCRIPTION
**Pull request by cstamas**
Many feature blindly assume (as Maven validates this) that `repository.id` is "path segment"-safe string.

Still, we found some fairly recent POMs (like maven-core 3.6.1!) that contain in their transitive hull POMs that contain FS unsafe repository IDs.

These IDs makes features like split repository, or metadata caching go hay-way.

This PR contains fix for these "bad" repository.id-s (by "fixing" them to be as should: FS safe) covering all places where repository.id is to be used as path segment.

Fixes #1564

### CODE REVIEW

**Comment by cstamas** [comment]
Local testing: 
* build this PR fully w/ ITs
* after the build, the "demos" local repository (`maven-resolver-demo-snippets/target/local-repo/.meta/resolver-status.properties` file) will contain "rewritten `oss.sonatype.orgXjboss-snapshots` repo ID `` instead of illegal `oss.sonatype.org/jboss-snapshots`

File: maven-resolver-util/src/main/java/org/eclipse/aether/util/repository/RepositoryIdHelper.java [hunk 1]
```diff
@@ -0,0 +1,108 @@
...
+     * see {@link #cachedIdToPathSegment(RepositorySystemSession)} method.
+     * <p>
+     * This method is visible for testing only, should not be used in any other scenarios.
+     *
+     * @see #cachedIdToPathSegment(RepositorySystemSession)
+     */
+    static String idToPathSegment(ArtifactRepository repository) {
+        if (repository instanceof RemoteRepository) {
+            StringBuilder result = new StringBuilder(repository.getId());
+            for (int illegalIndex = 0; illegalIndex < ILLEGAL_REPO_ID_CHARS.size(); illegalIndex++) {
```
Comment (gnodet) [inline maven-resolver-util/src/main/java/org/eclipse/aether/util/repository/RepositoryIdHelper.java]: This looks overly complicated.
I'd replace all invalid chars with '-' instead of 'X' and remove the possibility to define different chars.  Especially as this is not configurable.
The loop may be simplified once the above is done, maybe using replaceAll? Not sure...

Comment (cstamas) [reply maven-resolver-util/src/main/java/org/eclipse/aether/util/repository/RepositoryIdHelper.java]: The whole point is this happens in cached call, so as javadoc notes, this method is "is (intentionally) simplistic on purpose", but is not public either, calling it is possible _only via cached one_. 

As for "X" vs "-" vs whatever, is really just matter of taste, as I was even toying to do something like this:
```
| -> PIPE
: -> COLON
/ -> SLASH
\ -> BACKSLASH
...
```
so basically it would be clear (but still "path segment safe") that this ID is "weird".

Comment (cstamas) [reply maven-resolver-util/src/main/java/org/eclipse/aether/util/repository/RepositoryIdHelper.java]: Doing that "dict replace" would in fact make different from IDs still unique, as now `repo/id` and `repo:id` both maps to `repoXid`, while in latter case those would be `repoCOLONid` and `repoSLASHid`

Comment (gnodet) [reply maven-resolver-util/src/main/java/org/eclipse/aether/util/repository/RepositoryIdHelper.java]: "X" vs "-" is a matter of readability, more than taste.  Anything that's not a letter will be easier to read to separate groups of letters.

I'd be fine with specific words, but again for readability, I'd move them between `-` or `_`:  
  `foo/bar` -> `foo_SLASH_bar`
  
  That would be fine imho, especially to keep the ID unique as you indicate.

Comment (cstamas) [reply maven-resolver-util/src/main/java/org/eclipse/aether/util/repository/RepositoryIdHelper.java]: pushed "dict", and separators are needed next

Comment (cstamas) [reply maven-resolver-util/src/main/java/org/eclipse/aether/util/repository/RepositoryIdHelper.java]: added separators to replacement strings, hopefully we will never deal with "bad IDs" like in UT: `"\\/:\"<>|?*"` to worry about neighboring separators :smile:

Comment (cstamas) [reply maven-resolver-util/src/main/java/org/eclipse/aether/util/repository/RepositoryIdHelper.java]: In fact: this makes function reversible, so is even better. Again, this is not for "human readability" but more to not make features like split repo and metadata caching "wander" to wrong dirs on your disk.

Comment (cstamas) [reply maven-resolver-util/src/main/java/org/eclipse/aether/util/repository/RepositoryIdHelper.java]: In other word, this feature is used ONLY when resolver is about to use repository.id as path segment... nowhere else. Exceptions and log messages still use "raw" repo IDs.

**Review by gnodet — APPROVED** [review]
